MagicLight Controller: STM32F10x_System_Private_Functions
STM32F10x_System_Private_Functions
Stm32f10x_system
Functions
void SystemInit (void)
Setup the microcontroller system Initialize the Embedded Flash Interface, the PLL and update the SystemCoreClock variable.
void SystemCoreClockUpdate (void)
Update SystemCoreClock variable according to Clock Register Values. The SystemCoreClock variable contains the core clock (HCLK), it can be used by the user application to setup the SysTick timer or configure other parameters.
static void SetSysClock (void)
Configures the System clock frequency, HCLK, PCLK2 and PCLK1 prescalers.
static void SetSysClockTo72 (void)
Setup the external memory controller. Called in startup_stm32f10x.s before jump to __main.
Detailed Description
Function Documentation
static void SetSysClock (void) static
Configures the System clock frequency, HCLK, PCLK2 and PCLK1 prescalers.
Return values
None
Definition at line 417 of file system_stm32f10x.c.
References SetSysClockTo72().
Referenced by SystemInit().
static void SetSysClockTo72 (void) static
Setup the external memory controller. Called in startup_stm32f10x.s before jump to __main.
Parameters
None
Return values
None Sets System clock frequency to 72MHz and configure HCLK, PCLK2 and PCLK1 prescalers.
Note
This function should be used only after reset.
Return values
None
Definition at line 984 of file system_stm32f10x.c.
Referenced by SetSysClock().
void SystemCoreClockUpdate (void)
Update SystemCoreClock variable according to Clock Register Values. The SystemCoreClock variable contains the core clock (HCLK), it can be used by the user application to setup the SysTick timer or configure other parameters.
Note
Each time the core clock (HCLK) changes, this function must be called to update SystemCoreClock variable value. Otherwise, any configuration based on this variable will be incorrect.
- The system frequency computed by this function is not the real frequency in the chip. It is calculated based on the predefined constant and the selected clock source:
If SYSCLK source is HSI, SystemCoreClock will contain the HSI_VALUE(*)
If SYSCLK source is HSE, SystemCoreClock will contain the HSE_VALUE(**)
If SYSCLK source is PLL, SystemCoreClock will contain the HSE_VALUE(**) or HSI_VALUE(*) multiplied by the PLL factors.
(*) HSI_VALUE is a constant defined in stm32f1xx.h file (default value 8 MHz) but the real value may vary depending on the variations in voltage and temperature.
(**) HSE_VALUE is a constant defined in stm32f1xx.h file (default value 8 MHz or 25 MHz, depedning on the product used), user has to ensure that HSE_VALUE is same as the real frequency of the crystal used. Otherwise, this function may have wrong result.
The result of this function could be not correct when using fractional value for HSE crystal.
Return values
None
Definition at line 305 of file system_stm32f10x.c.
References AHBPrescTable, and SystemCoreClock.
void SystemInit (void)
Setup the microcontroller system Initialize the Embedded Flash Interface, the PLL and update the SystemCoreClock variable.
Note
This function should be used only after reset.
Return values
None
Definition at line 212 of file system_stm32f10x.c.
References SetSysClock(), and VECT_TAB_OFFSET.