MagicLight Controller: UART1_Private_Functions
UART1_Private_Functions
ADC_Library
Functions
void p_IO_Init (void)
void p_NVIC_Init (void)
Detailed Description
Function Documentation
void p_IO_Init (void)
Definition at line 33 of file adc.c.
References GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AIN, GPIO_InitTypeDef::GPIO_Pin, GPIO_Pin_3, GPIO_Pin_4, GPIO_Pin_5, RCC_ADCCLKConfig(), RCC_APB2Periph_ADC1, RCC_APB2Periph_ADC2, RCC_APB2Periph_ADC3, RCC_APB2Periph_GPIOA, RCC_APB2PeriphClockCmd(), and RCC_PCLK2_Div4.
Referenced by ADC12_Init().
void p_NVIC_Init (void)
Definition at line 52 of file adc.c.
References NVIC_Init(), NVIC_InitTypeDef::NVIC_IRQChannel, NVIC_InitTypeDef::NVIC_IRQChannelCmd, NVIC_InitTypeDef::NVIC_IRQChannelPreemptionPriority, and NVIC_InitTypeDef::NVIC_IRQChannelSubPriority.