MagicLight Controller: UART1_Exported_Functions_Prototypes
UART1_Exported_Functions_Prototypes
ADC_Library | UART1_Library
Functions
void ADC12_Init (void)
This function initializes the ADC.
uint16_t ADC_GetValue (uint8_t filter)
This function returns value of the selected filter from ADC_FILTER.
void USART1_Init (uint32_t baudrate)
Initializes USART1.
void USART1_Put (uint8_t ch)
Puts a byte to USART1.
uint8_t USART1_Get (void)
Gets one byte from USART1.
void USART1_Puts (volatile char *s)
Put string to USART1.
void ML_SendPacket (int adr, char *msg)
Sends CRC ML Packet over USART1.
void ML_CMD_EffectList (void)
Sends the Effect List over USART1.
void ML_CMD_SettingsList (uint8_t ch)
Sends Settings List to USART1.
int ML_Parse_CRC_Command (const char *input, char *command, uint8_t *fchan, uint16_t *fpar)
Parses CRC ML Packet Command with Trailing Values.
int ML_GetNewCommand (void)
Return 1 if new command exists.
char * ML_GetCommand (void)
Returns the new Command if received.
bool ML_CheckNewCommand (const char *input)
Checks if a new command is received and valid.
void ML_ParseCommands (void)
General Parse Function for USART1.
void USART1_SetATmode (bool state)
Sets AT Mode for Bluetooth Module.
int USART1_IsAtMode (void)
Returns AT Mode Setting.
void Log (uint8_t level, char *msg)
Logs Message to USART1 with Verbose Level.
Detailed Description
Function Documentation
void ADC12_Init (void)
This function initializes the ADC.
Return values
None
Definition at line 74 of file adc.c.
References ADC_Channel_5, ADC_Cmd(), ADC_InitTypeDef::ADC_ContinuousConvMode, ADC_InitTypeDef::ADC_DataAlign, ADC_DataAlign_Right, ADC_InitTypeDef::ADC_ExternalTrigConv, ADC_ExternalTrigConv_None, ADC_GetCalibrationStatus(), ADC_GetResetCalibrationStatus(), ADC_Init(), ADC_InitTypeDef::ADC_Mode, ADC_Mode_Independent, ADC_InitTypeDef::ADC_NbrOfChannel, ADC_RegularChannelConfig(), ADC_ResetCalibration(), ADC_SampleTime_28Cycles5, ADC_InitTypeDef::ADC_ScanConvMode, ADC_StartCalibration(), and p_IO_Init().
Referenced by main().
uint16_t ADC_GetValue (uint8_t filter)
This function returns value of the selected filter from ADC_FILTER.
Parameters
filter The Filter to read out
Return values
ADC Value of Filter
Definition at line 115 of file adc.c.
References ADC_Channel_3, ADC_Channel_4, ADC_Channel_5, ADC_ClearFlag(), ADC_FLAG_EOC, ADC_GetConversionValue(), ADC_GetFlagStatus(), ADC_RegularChannelConfig(), ADC_SampleTime_7Cycles5, ADC_SoftwareStartConvCmd(), FILTER_HIGH, FILTER_LOW, and FILTER_MEDIUM.
void Log (uint8_t level, char * msg)
Logs Message to USART1 with Verbose Level.
Parameters
level Verbose Level to use
msg Message to Send
Return values
None
Note
Add \r\n for breaks
Definition at line 105 of file uart1.c.
References VERBOSE.
Referenced by d_printArray(), main(), ML_CheckNewCommand(), ML_Parse_CRC_Command(), ML_ParseCommands(), and p_WS2812_InitDMA().
bool ML_CheckNewCommand (const char * input)
Checks if a new command is received and valid.
Parameters
input Pointer to String with CRC coded input value
Return values
Returns true if CRC was ok
Definition at line 467 of file uart1.c.
References buf, and Log().
void ML_CMD_EffectList (void)
Sends the Effect List over USART1.
Return values
None
Definition at line 277 of file uart1.c.
References buf, effects, MAX_EFFECTS, and ML_SendPacket().
Referenced by ML_ParseCommands().
void ML_CMD_SettingsList (uint8_t ch)
Sends Settings List to USART1.
Parameters
ch LED Channel to get settings from
Return values
None
Definition at line 304 of file uart1.c.
References buf, and ML_SendPacket().
Referenced by ML_ParseCommands().
char* ML_GetCommand (void)
Returns the new Command if received.
Return values
Returns the Command as char pointer
Definition at line 455 of file uart1.c.
References UART::Command, and UART::NewCommand.
Referenced by ML_ParseCommands().
int ML_GetNewCommand (void)
Return 1 if new command exists.
Return values
Existing of new Command (1 for exists)
Definition at line 435 of file uart1.c.
References UART::NewCommand.
Referenced by ML_ParseCommands().
int ML_Parse_CRC_Command (const char * input, char * command, uint8_t * fchan, uint16_t * fpar)
Parses CRC ML Packet Command with Trailing Values.
Parameters
input Input String as Pointer
command Command Pointer to put received command in
fchan Received LED Channel value
fpar Received parameter for function
Return values
None
Definition at line 325 of file uart1.c.
References buf, and Log().
Referenced by ML_ParseCommands().
void ML_ParseCommands (void)
General Parse Function for USART1.
Return values
None
Definition at line 515 of file uart1.c.
References all_chan, BLUETOOTH_CONNECTION, buf, command, control_type, d_printArray(), fchan, fpar, LED_FADEOUT_SPEED, Log(), MAX_BRIGHT, MAX_CHANNELS, MAX_DELAY, MAX_EFFECTS, MAX_HUE, MAX_SAT, ML_CMD_EffectList(), ML_CMD_SettingsList(), ML_GetCommand(), ML_GetNewCommand(), ML_Parse_CRC_Command(), CHANNEL::thisdelay, CHANNEL::thishue, CHANNEL::thisprogram, CHANNEL::thissat, CHANNEL::thisvalue, and TWI_CONNECTION.
void ML_SendPacket (int adr, char * msg)
Sends CRC ML Packet over USART1.
Parameters
adr Address Byte
Return values
msg Message to send
Definition at line 253 of file uart1.c.
Referenced by ML_CMD_EffectList(), and ML_CMD_SettingsList().
uint8_t USART1_Get (void)
Gets one byte from USART1.
Return values
None
Definition at line 221 of file uart1.c.
References USART_FLAG_RXNE, USART_GetFlagStatus(), and USART_ReceiveData().
void USART1_Init (uint32_t baudrate)
Initializes USART1.
Parameters
baudrate Baudrate to use
Return values
None
Definition at line 137 of file uart1.c.
References GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF_PP, GPIO_Mode_IN_FLOATING, GPIO_InitTypeDef::GPIO_Pin, GPIO_Pin_10, GPIO_Pin_9, GPIO_PinRemapConfig(), GPIO_Remap_USART1, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, UART::NewCommand, NVIC_Init(), NVIC_InitTypeDef::NVIC_IRQChannel, NVIC_InitTypeDef::NVIC_IRQChannelCmd, NVIC_InitTypeDef::NVIC_IRQChannelPreemptionPriority, NVIC_InitTypeDef::NVIC_IRQChannelSubPriority, NVIC_PriorityGroup_4, NVIC_PriorityGroupConfig(), RCC_APB2Periph_GPIOA, RCC_APB2Periph_USART1, RCC_APB2PeriphClockCmd(), USART_InitTypeDef::USART_BaudRate, USART_Cmd(), USART_DeInit(), USART_InitTypeDef::USART_HardwareFlowControl, USART_HardwareFlowControl_None, USART_Init(), USART_IT_RXNE, USART_ITConfig(), USART_InitTypeDef::USART_Mode, USART_Mode_Rx, USART_Mode_Tx, USART_InitTypeDef::USART_Parity, USART_Parity_No, USART_InitTypeDef::USART_StopBits, USART_StopBits_1, USART_InitTypeDef::USART_WordLength, and USART_WordLength_8b.
Referenced by main().
int USART1_IsAtMode (void)
Returns AT Mode Setting.
Return values
Returns true if AT Mode is set
Definition at line 445 of file uart1.c.
References atmode.
void USART1_Put (uint8_t ch)
Puts a byte to USART1.
Parameters
ch Byte to send
Return values
None
Definition at line 207 of file uart1.c.
References USART_FLAG_TC, USART_GetFlagStatus(), and USART_SendData().
void USART1_Puts (volatile char * s)
Put string to USART1.
Parameters
s String to send
Return values
None
Definition at line 234 of file uart1.c.
References USART_SendData().
void USART1_SetATmode (bool state)
Sets AT Mode for Bluetooth Module.
Parameters
state true for AT Mode enabled
Return values
None
Definition at line 117 of file uart1.c.
References atmode, GPIO_Pin_8, GPIO_ResetBits(), and GPIO_SetBits().
Referenced by main().