MagicLight Controller: DWT_Exported_Functions_Prototypes
DWT_Exported_Functions_Prototypes
DWT_Library
Functions
void DWT_Init (void)
Initializes the DWT.
uint32_t DWT_Get (void)
Returns the current ticks.
uint8_t DWT_Compare (int32_t tp)
Compares parameter with current ticks.
void DWT_Delay (uint32_t us)
Delays n microseconds.
void DWT_Delay_ms (uint16_t ms)
Delays n milliseconds.
uint32_t millis ()
Returns the actual count of milliseconds.
Detailed Description
Function Documentation
uint8_t DWT_Compare (int32_t tp)
Compares parameter with current ticks.
Parameters
tp Ticks to compare
Return values
true if comparison ok
Definition at line 57 of file dwt.c.
References DWT_Get().
Referenced by DWT_Delay().
void DWT_Delay (uint32_t us)
Delays n microseconds.
Parameters
us Microseconds to delay
Return values
None
Definition at line 67 of file dwt.c.
References DWT_Compare(), DWT_Get(), and SystemCoreClock.
Referenced by DWT_Delay_ms(), and main().
void DWT_Delay_ms (uint16_t ms)
Delays n milliseconds.
Parameters
ms Milliseconds to delay
Return values
None
Definition at line 82 of file dwt.c.
References DWT_Delay().
Referenced by main().
uint32_t DWT_Get (void)
Returns the current ticks.
Return values
Current CPU Ticks
Definition at line 46 of file dwt.c.
Referenced by DWT_Compare(), DWT_Delay(), and millis().
void DWT_Init (void)
Initializes the DWT.
Return values
None
Definition at line 31 of file dwt.c.
Referenced by main().
uint32_t millis ()
Returns the actual count of milliseconds.
Return values
Actual count of milliseconds
Definition at line 92 of file dwt.c.
References DWT_Get(), and SystemCoreClock.