MagicLight Controller: Library_I2C2_Exported_Functions
Library_I2C2_Exported_Functions
Functions
void USART1_Init (uint32_t baudrate)
Initializes USART1.
void USART1_Put (uint8_t ch)
Puts a byte to USART1.
uint8_t USART1_Get (void)
Gets one byte from USART1.
void USART1_Puts (volatile char *s)
Put string to USART1.
void send_ml_packet (int adr, char *msg)
Sends CRC ML Packet over USART1.
void cmd_effect_list (void)
Sends the Effect List over USART1.
void cmd_settings_list (uint8_t ch)
Sends Settings List to USART1.
int parse_crc_command_int (const char *input, char *command, uint8_t *fchan, uint16_t *fpar)
Parses CRC ML Packet Command with Trailing Values.
int getNewCommand (void)
Return 1 if new command exists.
char * getCommand (void)
Returns the new Command if received.
bool checkNewCommand (const char *input)
Checks if a new command is received and valid.
void parseCommands (void)
General Parse Function for USART1.
void USART1_SetATmode (bool state)
Sets AT Mode for Bluetooth Module.
int USART1_IsAtMode (void)
Returns AT Mode Setting.
void Log (uint8_t level, char *msg)
Logs Message to USART1 with Verbose Level.
Detailed Description
Function Documentation
bool checkNewCommand (const char * input)
Checks if a new command is received and valid.
Parameters
input Pointer to String with CRC coded input value
Return values
Returns true if CRC was ok
Definition at line 468 of file uart1.c.
References buf, and Log().
void cmd_effect_list (void)
Sends the Effect List over USART1.
Return values
None
Definition at line 278 of file uart1.c.
References buf, effects, MAX_EFFECTS, and send_ml_packet().
Referenced by parseCommands().
void cmd_settings_list (uint8_t ch)
Sends Settings List to USART1.
Parameters
ch LED Channel to get settings from
Return values
None
Definition at line 305 of file uart1.c.
References buf, and send_ml_packet().
Referenced by parseCommands().
char* getCommand (void)
Returns the new Command if received.
Return values
Returns the Command as char pointer
Definition at line 456 of file uart1.c.
References UART::Command, and UART::NewCommand.
Referenced by parseCommands().
int getNewCommand (void)
Return 1 if new command exists.
Return values
Existing of new Command (1 for exists)
Definition at line 436 of file uart1.c.
References UART::NewCommand.
Referenced by parseCommands().
void Log (uint8_t level, char * msg)
Logs Message to USART1 with Verbose Level.
Parameters
level Verbose Level to use
msg Message to Send
Return values
None
Note
Add \r\n for breaks
Definition at line 106 of file uart1.c.
References VERBOSE.
Referenced by checkNewCommand(), d_printArray(), main(), p_WS2812_InitDMA(), parse_crc_command_int(), and parseCommands().
int parse_crc_command_int (const char * input, char * command, uint8_t * fchan, uint16_t * fpar)
Parses CRC ML Packet Command with Trailing Values.
Parameters
input Input String as Pointer
command Command Pointer to put received command in
fchan Received LED Channel value
fpar Received parameter for function
Return values
None
Definition at line 326 of file uart1.c.
References buf, and Log().
Referenced by parseCommands().
void parseCommands (void)
General Parse Function for USART1.
Return values
None
Definition at line 516 of file uart1.c.
References all_chan, BLUETOOTH_CONNECTION, buf, cmd_effect_list(), cmd_settings_list(), command, control_type, d_printArray(), fchan, fpar, getCommand(), getNewCommand(), LED_FADEOUT_SPEED, Log(), MAX_BRIGHT, MAX_CHANNELS, MAX_DELAY, MAX_EFFECTS, MAX_HUE, MAX_SAT, parse_crc_command_int(), CHANNEL::thisdelay, CHANNEL::thishue, CHANNEL::thisprogram, CHANNEL::thissat, CHANNEL::thisvalue, and TWI_CONNECTION.
void send_ml_packet (int adr, char * msg)
Sends CRC ML Packet over USART1.
Parameters
adr Address Byte
Return values
msg Message to send
Definition at line 254 of file uart1.c.
Referenced by cmd_effect_list(), and cmd_settings_list().
uint8_t USART1_Get (void)
Gets one byte from USART1.
Return values
None
Definition at line 222 of file uart1.c.
References USART_FLAG_RXNE, USART_GetFlagStatus(), and USART_ReceiveData().
void USART1_Init (uint32_t baudrate)
Initializes USART1.
Parameters
baudrate Baudrate to use
Return values
None
Definition at line 138 of file uart1.c.
References GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF_PP, GPIO_Mode_IN_FLOATING, GPIO_InitTypeDef::GPIO_Pin, GPIO_Pin_10, GPIO_Pin_9, GPIO_PinRemapConfig(), GPIO_Remap_USART1, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, UART::NewCommand, NVIC_Init(), NVIC_InitTypeDef::NVIC_IRQChannel, NVIC_InitTypeDef::NVIC_IRQChannelCmd, NVIC_InitTypeDef::NVIC_IRQChannelPreemptionPriority, NVIC_InitTypeDef::NVIC_IRQChannelSubPriority, NVIC_PriorityGroup_4, NVIC_PriorityGroupConfig(), RCC_APB2Periph_GPIOA, RCC_APB2Periph_USART1, RCC_APB2PeriphClockCmd(), USART_InitTypeDef::USART_BaudRate, USART_Cmd(), USART_DeInit(), USART_InitTypeDef::USART_HardwareFlowControl, USART_HardwareFlowControl_None, USART_Init(), USART_IT_RXNE, USART_ITConfig(), USART_InitTypeDef::USART_Mode, USART_Mode_Rx, USART_Mode_Tx, USART_InitTypeDef::USART_Parity, USART_Parity_No, USART_InitTypeDef::USART_StopBits, USART_StopBits_1, USART_InitTypeDef::USART_WordLength, and USART_WordLength_8b.
Referenced by main().
int USART1_IsAtMode (void)
Returns AT Mode Setting.
Return values
Returns true if AT Mode is set
Definition at line 446 of file uart1.c.
References atmode.
void USART1_Put (uint8_t ch)
Puts a byte to USART1.
Parameters
ch Byte to send
Return values
None
Definition at line 208 of file uart1.c.
References USART_FLAG_TC, USART_GetFlagStatus(), and USART_SendData().
void USART1_Puts (volatile char * s)
Put string to USART1.
Parameters
s String to send
Return values
None
Definition at line 235 of file uart1.c.
References USART_SendData().
void USART1_SetATmode (bool state)
Sets AT Mode for Bluetooth Module.
Parameters
state true for AT Mode enabled
Return values
None
Definition at line 118 of file uart1.c.
References atmode, GPIO_Pin_8, GPIO_ResetBits(), and GPIO_SetBits().
Referenced by main().