MagicLight Controller: UB_Led_Exported_Functions_Prototypes
UB_Led_Exported_Functions_Prototypes
STM32_UB_Led
Functions
void UB_Led_Init (void)
Initializes all defined LED Sources.
void UB_Led_Off (LED_NAME_t led_name)
Switches specified LED off.
void UB_Led_On (LED_NAME_t led_name)
Switches specified LED on.
void UB_Led_Toggle (LED_NAME_t led_name)
Toggles specified LED.
void UB_Led_Switch (LED_NAME_t led_name, LED_STATUS_t wert)
Switches specified LED on or off.
Detailed Description
Function Documentation
void UB_Led_Init (void)
Initializes all defined LED Sources.
Return values
None
Definition at line 50 of file stm32_ub_led.c.
References GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_Out_PP, GPIO_InitTypeDef::GPIO_Pin, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, LED_ANZ, LED_OFF, LED_t::LED_PIN, RCC_APB2PeriphClockCmd(), UB_Led_Off(), and UB_Led_On().
Referenced by main().
void UB_Led_Off (LED_NAME_t led_name)
Switches specified LED off.
Parameters
led_name Constant LED name to switch
Return values
None
Definition at line 82 of file stm32_ub_led.c.
References GPIO_ResetBits().
Referenced by UB_Led_Init(), and UB_Led_Switch().
void UB_Led_On (LED_NAME_t led_name)
Switches specified LED on.
Parameters
led_name Constant LED name to switch
Return values
None
Definition at line 93 of file stm32_ub_led.c.
References GPIO_SetBits().
Referenced by UB_Led_Init(), and UB_Led_Switch().
void UB_Led_Switch (LED_NAME_t led_name, LED_STATUS_t wert)
Switches specified LED on or off.
Parameters
led_name Constant LED name to switch
wert Constant LED Status to set
Return values
None
Definition at line 119 of file stm32_ub_led.c.
References LED_OFF, UB_Led_Off(), and UB_Led_On().
void UB_Led_Toggle (LED_NAME_t led_name)
Toggles specified LED.
Parameters
led_name Constant LED name to toggle
Return values
None
Definition at line 104 of file stm32_ub_led.c.
References GPIO_ReadInputDataBit(), GPIO_ResetBits(), and GPIO_SetBits().
Referenced by main().