MagicLight Controller: MISC_Private_Functions
MISC_Private_Functions
MISC
Functions
void NVIC_PriorityGroupConfig (uint32_t NVIC_PriorityGroup)
Configures the priority grouping: pre-emption priority and subpriority.
void NVIC_Init (NVIC_InitTypeDef *NVIC_InitStruct)
Initializes the NVIC peripheral according to the specified parameters in the NVIC_InitStruct.
void NVIC_SetVectorTable (uint32_t NVIC_VectTab, uint32_t Offset)
Sets the vector table location and Offset.
void NVIC_SystemLPConfig (uint8_t LowPowerMode, FunctionalState NewState)
Selects the condition for the system to enter low power mode.
void SysTick_CLKSourceConfig (uint32_t SysTick_CLKSource)
Configures the SysTick clock source.
Detailed Description
Function Documentation
void NVIC_Init (NVIC_InitTypeDef * NVIC_InitStruct)
Initializes the NVIC peripheral according to the specified parameters in the NVIC_InitStruct.
Parameters
NVIC_InitStruct pointer to a NVIC_InitTypeDef structure that contains the configuration information for the specified NVIC peripheral.
Return values
None
Definition at line 112 of file misc.c.
References assert_param, IS_NVIC_PREEMPTION_PRIORITY, IS_NVIC_SUB_PRIORITY, NVIC_InitTypeDef::NVIC_IRQChannel, NVIC_InitTypeDef::NVIC_IRQChannelCmd, NVIC_InitTypeDef::NVIC_IRQChannelPreemptionPriority, and NVIC_InitTypeDef::NVIC_IRQChannelSubPriority.
Referenced by p_NVIC_Init(), p_WS2812_InitNVIC(), and USART1_Init().
void NVIC_PriorityGroupConfig (uint32_t NVIC_PriorityGroup)
Configures the priority grouping: pre-emption priority and subpriority.
Parameters
NVIC_PriorityGroup specifies the priority grouping bits length. This parameter can be one of the following values:
NVIC_PriorityGroup_0: 0 bits for pre-emption priority 4 bits for subpriority
NVIC_PriorityGroup_1: 1 bits for pre-emption priority 3 bits for subpriority
NVIC_PriorityGroup_2: 2 bits for pre-emption priority 2 bits for subpriority
NVIC_PriorityGroup_3: 3 bits for pre-emption priority 1 bits for subpriority
NVIC_PriorityGroup_4: 4 bits for pre-emption priority 0 bits for subpriority
Return values
None
Definition at line 96 of file misc.c.
References AIRCR_VECTKEY_MASK, assert_param, and IS_NVIC_PRIORITY_GROUP.
Referenced by USART1_Init().
void NVIC_SetVectorTable (uint32_t NVIC_VectTab, uint32_t Offset)
Sets the vector table location and Offset.
Parameters
NVIC_VectTab specifies if the vector table is in RAM or FLASH memory. This parameter can be one of the following values:
NVIC_VectTab_RAM
NVIC_VectTab_FLASH
Offset Vector Table base offset field. This value must be a multiple of 0x200.
Return values
None
Definition at line 156 of file misc.c.
References assert_param, IS_NVIC_OFFSET, and IS_NVIC_VECTTAB.
Referenced by NVIC_Configuration().
void NVIC_SystemLPConfig (uint8_t LowPowerMode, FunctionalState NewState)
Selects the condition for the system to enter low power mode.
Parameters
LowPowerMode Specifies the new mode for the system to enter low power mode. This parameter can be one of the following values:
NVIC_LP_SEVONPEND
NVIC_LP_SLEEPDEEP
NVIC_LP_SLEEPONEXIT
NewState new state of LP condition. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 175 of file misc.c.
References assert_param, and IS_NVIC_LP.
void SysTick_CLKSourceConfig (uint32_t SysTick_CLKSource)
Configures the SysTick clock source.
Parameters
SysTick_CLKSource specifies the SysTick clock source. This parameter can be one of the following values:
SysTick_CLKSource_HCLK_Div8: AHB clock divided by 8 selected as SysTick clock source.
SysTick_CLKSource_HCLK: AHB clock selected as SysTick clock source.
Return values
None
Definition at line 199 of file misc.c.
References assert_param, IS_SYSTICK_CLK_SOURCE, SysTick_CLKSource_HCLK, and SysTick_CLKSource_HCLK_Div8.