MagicLight Controller: I2C2_Private_Functions
I2C2_Private_Functions
I2C2_Library
Functions
void P_I2C2_InitI2C (void)
This funtion initializes the I2C Interface.
int16_t P_I2C2_timeout (int16_t wert)
This funtion will be called upon a timeout and stops, reset and reinit the I2C Interface.
Detailed Description
Function Documentation
void P_I2C2_InitI2C (void)
This funtion initializes the I2C Interface.
Return values
None
Definition at line 386 of file i2c2.c.
References I2C2_CLOCK_FRQ, I2C_InitTypeDef::I2C_Ack, I2C_Ack_Disable, I2C_InitTypeDef::I2C_AcknowledgedAddress, I2C_AcknowledgedAddress_7bit, I2C_InitTypeDef::I2C_ClockSpeed, I2C_Cmd(), I2C_DeInit(), I2C_InitTypeDef::I2C_DutyCycle, I2C_DutyCycle_2, I2C_Init(), I2C_InitTypeDef::I2C_Mode, I2C_Mode_I2C, and I2C_InitTypeDef::I2C_OwnAddress1.
Referenced by I2C2_Init(), and P_I2C2_timeout().
int16_t P_I2C2_timeout (int16_t wert)
This funtion will be called upon a timeout and stops, reset and reinit the I2C Interface.
Parameters
wert Nothing special
Return values
None
Definition at line 420 of file i2c2.c.
References I2C_DeInit(), I2C_GenerateSTOP(), I2C_SoftwareResetCmd(), and P_I2C2_InitI2C().
Referenced by I2C2_ReadByte(), and I2C2_WriteByte().