MagicLight Controller: I2C2_Exported_Functions
I2C2_Exported_Functions
I2C2_Library
Functions
void I2C2_Init (void)
Initializes I2C2 Periph.
int16_t I2C2_ReadByte (uint8_t slave_adr, uint8_t adr)
Read address from I2C Slave.
int16_t I2C2_WriteByte (uint8_t slave_adr, uint8_t adr, uint8_t wert)
Initializes all defined LED Sources.
void I2C2_Delay (volatile uint32_t nCount)
Small delay without Timer usage.
void I2C2_Start (uint8_t address, uint8_t direction)
This function issues a start condition and transmits the slave address + R/W bit.
void I2C2_Write (uint8_t data)
This function transmits one byte to the slave device.
uint8_t I2C2_Read_Ack (void)
This function reads one byte from the slave device and acknowledges the byte (requests another byte).
uint8_t I2C2_Read_Nack (void)
This function reads one byte from the slave device and doesn't acknowledge the recieved data.
void I2C2_Stop (void)
This funtion issues a stop condition and therefore releases the bus.
Detailed Description
Function Documentation
void I2C2_Delay (volatile uint32_t nCount)
Small delay without Timer usage.
Parameters
nCount Count time for delay
Return values
None
Definition at line 258 of file i2c2.c.
void I2C2_Init (void)
Initializes I2C2 Periph.
Return values
None
Definition at line 64 of file i2c2.c.
References I2C2_PIN_t::CLK, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF_OD, GPIO_InitTypeDef::GPIO_Pin, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, P_I2C2_InitI2C(), I2C2_PIN_t::PIN, I2C2_PIN_t::PORT, RCC_APB1Periph_I2C2, RCC_APB1PeriphClockCmd(), RCC_APB1PeriphResetCmd(), RCC_APB2PeriphClockCmd(), I2C2_DEV_t::SCL, and I2C2_DEV_t::SDA.
Referenced by main().
uint8_t I2C2_Read_Ack (void)
This function reads one byte from the slave device and acknowledges the byte (requests another byte).
Return values
the read byte
Definition at line 326 of file i2c2.c.
References I2C_AcknowledgeConfig(), I2C_CheckEvent(), I2C_EVENT_MASTER_BYTE_RECEIVED, and I2C_ReceiveData().
uint8_t I2C2_Read_Nack (void)
This function reads one byte from the slave device and doesn't acknowledge the recieved data.
Return values
the read byte
Definition at line 344 of file i2c2.c.
References I2C_AcknowledgeConfig(), I2C_CheckEvent(), I2C_EVENT_MASTER_BYTE_RECEIVED, I2C_GenerateSTOP(), and I2C_ReceiveData().
int16_t I2C2_ReadByte (uint8_t slave_adr, uint8_t adr)
Read address from I2C Slave.
Parameters
slave_adr I2C Base Adress
adr Registers to read
Return values
Byte with read value (-1 = error)
Definition at line 114 of file i2c2.c.
References I2C2_TIMEOUT, I2C_AcknowledgeConfig(), I2C_Direction_Receiver, I2C_Direction_Transmitter, I2C_FLAG_ADDR, I2C_FLAG_BTF, I2C_FLAG_RXNE, I2C_FLAG_SB, I2C_FLAG_TXE, I2C_GenerateSTART(), I2C_GenerateSTOP(), I2C_GetFlagStatus(), I2C_ReceiveData(), I2C_Send7bitAddress(), I2C_SendData(), and P_I2C2_timeout().
void I2C2_Start (uint8_t address, uint8_t direction)
This function issues a start condition and transmits the slave address + R/W bit.
Parameters
address the 7 bit slave address
direction the tranmission direction can be: I2C_Direction_Transmitter for Master transmitter mode I2C_Direction_Receiver for Master receiver
Return values
None
Definition at line 275 of file i2c2.c.
References I2C_CheckEvent(), I2C_Direction_Receiver, I2C_Direction_Transmitter, I2C_EVENT_MASTER_MODE_SELECT, I2C_EVENT_MASTER_RECEIVER_MODE_SELECTED, I2C_EVENT_MASTER_TRANSMITTER_MODE_SELECTED, I2C_FLAG_BUSY, I2C_GenerateSTART(), I2C_GetFlagStatus(), and I2C_Send7bitAddress().
void I2C2_Stop (void)
This funtion issues a stop condition and therefore releases the bus.
Return values
None
Definition at line 365 of file i2c2.c.
References I2C_GenerateSTOP().
void I2C2_Write (uint8_t data)
This function transmits one byte to the slave device.
Parameters
data the Data Byte to be transmitted
Return values
None
Definition at line 309 of file i2c2.c.
References I2C_CheckEvent(), I2C_EVENT_MASTER_BYTE_TRANSMITTED, and I2C_SendData().
int16_t I2C2_WriteByte (uint8_t slave_adr, uint8_t adr, uint8_t wert)
Initializes all defined LED Sources.
Parameters
slave_adr I2C Base Address
adr Register Address to write
wert Byte to write
Return values
0 for OK, <0 for Error
Definition at line 199 of file i2c2.c.
References I2C2_TIMEOUT, I2C_Direction_Transmitter, I2C_FLAG_ADDR, I2C_FLAG_BTF, I2C_FLAG_SB, I2C_FLAG_TXE, I2C_GenerateSTART(), I2C_GenerateSTOP(), I2C_GetFlagStatus(), I2C_Send7bitAddress(), I2C_SendData(), and P_I2C2_timeout().