MagicLight Controller: EXTI_Private_Functions
EXTI_Private_Functions
EXTI
Functions
void EXTI_DeInit (void)
Deinitializes the EXTI peripheral registers to their default reset values.
void EXTI_Init (EXTI_InitTypeDef *EXTI_InitStruct)
Initializes the EXTI peripheral according to the specified parameters in the EXTI_InitStruct.
void EXTI_StructInit (EXTI_InitTypeDef *EXTI_InitStruct)
Fills each EXTI_InitStruct member with its reset value.
void EXTI_GenerateSWInterrupt (uint32_t EXTI_Line)
Generates a Software interrupt.
FlagStatus EXTI_GetFlagStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line flag is set or not.
void EXTI_ClearFlag (uint32_t EXTI_Line)
Clears the EXTI's line pending flags.
ITStatus EXTI_GetITStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line is asserted or not.
void EXTI_ClearITPendingBit (uint32_t EXTI_Line)
Clears the EXTI's line pending bits.
Detailed Description
Function Documentation
void EXTI_ClearFlag (uint32_t EXTI_Line)
Clears the EXTI's line pending flags.
Parameters
EXTI_Line specifies the EXTI lines flags to clear. This parameter can be any combination of EXTI_Linex where x can be (0..19).
Return values
None
Definition at line 209 of file stm32f10x_exti.c.
References assert_param, and IS_EXTI_LINE.
void EXTI_ClearITPendingBit (uint32_t EXTI_Line)
Clears the EXTI's line pending bits.
Parameters
EXTI_Line specifies the EXTI lines to clear. This parameter can be any combination of EXTI_Linex where x can be (0..19).
Return values
None
Definition at line 249 of file stm32f10x_exti.c.
References assert_param, and IS_EXTI_LINE.
Referenced by EXTI9_5_IRQHandler().
void EXTI_DeInit (void)
Deinitializes the EXTI peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 85 of file stm32f10x_exti.c.
void EXTI_GenerateSWInterrupt (uint32_t EXTI_Line)
Generates a Software interrupt.
Parameters
EXTI_Line specifies the EXTI lines to be enabled or disabled. This parameter can be any combination of EXTI_Linex where x can be (0..19).
Return values
None
Definition at line 171 of file stm32f10x_exti.c.
References assert_param, and IS_EXTI_LINE.
FlagStatus EXTI_GetFlagStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line flag is set or not.
Parameters
EXTI_Line specifies the EXTI line flag to check. This parameter can be:
EXTI_Linex: External interrupt line x where x(0..19)
Return values
The new state of EXTI_Line (SET or RESET).
Definition at line 186 of file stm32f10x_exti.c.
References assert_param, and IS_GET_EXTI_LINE.
ITStatus EXTI_GetITStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line is asserted or not.
Parameters
EXTI_Line specifies the EXTI line to check. This parameter can be:
EXTI_Linex: External interrupt line x where x(0..19)
Return values
The new state of EXTI_Line (SET or RESET).
Definition at line 224 of file stm32f10x_exti.c.
References assert_param, and IS_GET_EXTI_LINE.
Referenced by EXTI9_5_IRQHandler().
void EXTI_Init (EXTI_InitTypeDef * EXTI_InitStruct)
Initializes the EXTI peripheral according to the specified parameters in the EXTI_InitStruct.
Parameters
EXTI_InitStruct pointer to a EXTI_InitTypeDef structure that contains the configuration information for the EXTI peripheral.
Return values
None
Definition at line 101 of file stm32f10x_exti.c.
References assert_param, EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_InitTypeDef::EXTI_Trigger, EXTI_Trigger_Rising_Falling, IS_EXTI_LINE, IS_EXTI_MODE, and IS_EXTI_TRIGGER.
Referenced by p_WS2812_InitEXTI().
void EXTI_StructInit (EXTI_InitTypeDef * EXTI_InitStruct)
Fills each EXTI_InitStruct member with its reset value.
Parameters
EXTI_InitStruct pointer to a EXTI_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 157 of file stm32f10x_exti.c.
References EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_LINENONE, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, and EXTI_Trigger_Falling.