MagicLight Controller: src/main.c File Reference
main.c File Reference
This file includes the general init functions and the main()-function.
#include "main.h"
#include "stm32_ub_led.h"
#include "stm32_ub_ws2812.h"
Functions
void IO_Init (void)
void Init_Channels (void)
void RCC_Configuration (void)
void NVIC_Configuration (void)
void Delay (vu32 nCount)
int main (void)
Mainfunction.
void assert_failed (u8 *file, u32 line)
Variables
uint32_t SystemCoreClock
ErrorStatus HSEStartUpStatus
uint8_t control_type
char buf [128]
Detailed Description
This file includes the general init functions and the main()-function.
Author
Michael Sauer sauer.nosp@m..uet.nosp@m.ersen.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
30.08.2014 - First Version (Clone of ml_mainunit.c)
16.09.2014 - I2C added
Todo:
Effect rework
ADC to DMA / Interrupt
I2C initializing
Shell commands
Definition in file main.c.
Function Documentation
void assert_failed (u8 * file, u32 line)
Definition at line 509 of file main.c.
void Delay (vu32 nCount)
Definition at line 493 of file main.c.
void Init_Channels (void)
Definition at line 368 of file main.c.
References CHANNEL::bgColor, CHANNEL::bgColorSet, CHANNEL::blank, CHANNEL::BOTTOM_INDEX, CHANNEL::bouncedirection, channel, CHANNEL::EVENODD, CHANNEL::fade, CHANNEL::ibright, CHANNEL::idex, CHANNEL::ihue, CHANNEL::isat, CHANNEL::j, CHANNEL::led_count, MAX_CHANNELS, CHANNEL::max_val0, CHANNEL::max_val1, CHANNEL::max_val2, CHANNEL::MIDDLE_INDEX, CHANNEL::offset, CHANNEL::thisdelay, CHANNEL::thishue, CHANNEL::thisprogram, CHANNEL::thissat, CHANNEL::thisvalue, CHANNEL::welle, and CHANNEL::wellen.
void IO_Init (void)
Definition at line 332 of file main.c.
References GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AIN, GPIO_Mode_IPD, GPIO_Mode_IPU, GPIO_Mode_Out_PP, GPIO_InitTypeDef::GPIO_Pin, GPIO_Pin_11, GPIO_Pin_13, GPIO_Pin_2, GPIO_Pin_8, GPIO_ResetBits(), GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, RCC_APB2Periph_GPIOA, RCC_APB2Periph_GPIOC, and RCC_APB2PeriphClockCmd().
Referenced by main().
int main (void)
Mainfunction.
This is the main routine that would be run after reset of the controller
TIM3-CH1 = PA6 / OK TIM3-CH2 = PA1 / OK !!! TIM3-CH3 = PB0 / PC8 TIM3-CH4 = PB1 / PC9
Definition at line 106 of file main.c.
References ADC12_Init(), BLUETOOTH_NAME, BLUETOOTH_PIN, BLUETOOTH_UART, buf, DWT_Delay(), DWT_Delay_ms(), DWT_Init(), GPIO_Pin_13, GPIO_ReadInputDataBit(), I2C2_Init(), IO_Init(), LED_1, Led_On, Log(), NVIC_Configuration(), RCC_Configuration(), UB_Led_Init(), UB_Led_Toggle(), UB_WS2812_Init(), USART1_Init(), USART1_SetATmode(), VER_BUILD, VER_MAJOR, and VER_MINOR.
void NVIC_Configuration (void)
Definition at line 475 of file main.c.
References NVIC_SetVectorTable(), NVIC_VectTab_FLASH, and NVIC_VectTab_RAM.
Referenced by main().
void RCC_Configuration (void)
Definition at line 409 of file main.c.
References FLASH_Latency_2, FLASH_PrefetchBuffer_Enable, FLASH_PrefetchBufferCmd(), FLASH_SetLatency(), HSEStartUpStatus, RCC_DeInit(), RCC_FLAG_PLLRDY, RCC_GetFlagStatus(), RCC_GetSYSCLKSource(), RCC_HCLK_Div1, RCC_HCLK_Div2, RCC_HCLKConfig(), RCC_HSE_ON, RCC_HSEConfig(), RCC_PCLK1Config(), RCC_PCLK2Config(), RCC_PLLCmd(), RCC_PLLConfig(), RCC_PLLMul_9, RCC_PLLSource_HSE_Div1, RCC_SYSCLK_Div1, RCC_SYSCLKConfig(), RCC_SYSCLKSource_PLLCLK, and RCC_WaitForHSEStartUp().
Referenced by main().
Variable Documentation
char buf[128]
Definition at line 89 of file main.c.
Referenced by d_printArray(), main(), ML_CheckNewCommand(), ML_CMD_EffectList(), ML_CMD_SettingsList(), ML_Parse_CRC_Command(), ML_ParseCommands(), and p_WS2812_InitDMA().
uint8_t control_type
Definition at line 88 of file main.c.
ErrorStatus HSEStartUpStatus
Definition at line 87 of file main.c.
Referenced by RCC_Configuration().
uint32_t SystemCoreClock
Definition at line 86 of file main.c.