MagicLight Controller: ub_lib/stm32_ub_ws2812.c File Reference
stm32_ub_ws2812.c File Reference
This file includes the ws2812 LED functions Module: GPIO, TIM, DMA, MISC, EXTI, SYSCFG.
#include "stm32_ub_ws2812.h"
#include "stm32_ub_led.h"
#include "general.h"
#include "uart1.h"
#include <stdlib.h>
#include <stdio.h>
Functions
void p_WS2812_clearAll (void)
void p_WS2812_clearBuff (void)
void p_WS2812_calcTimerBuf (uint8_t mode)
void p_WS2812_InitIO (void)
void p_WS2812_InitTIM (void)
void p_WS2812_InitDMA (void)
void p_WS2812_InitNVIC (void)
void p_WS2812_InitEXTI (void)
void p_WS2812_DMA_Start (void)
ErrorStatus UB_WS2812_Init (void)
void UB_WS2812_SetPixel (uint8_t ch, uint16_t pixel, uint8_t red, uint8_t green, uint8_t blue)
void UB_WS2812_ClearChannel (uint8_t ch)
void UB_WS2812_SetChannel (uint8_t ch)
void UB_WS2812_FadeOut (uint8_t ch, uint8_t numfade, uint8_t count)
void UB_WS2812_Refresh (void)
void UB_WS2812_RGB_2_HSV (WS2812_HSV_t hsv_col, WS2812_RGB_t *rgb_col)
void UB_WS2812_One_Led_RGB (uint32_t nr, WS2812_RGB_t rgb_col, uint8_t refresh)
void UB_WS2812_All_Led_RGB (WS2812_RGB_t rgb_col, uint8_t refresh)
void UB_WS2812_One_Led_HSV (uint32_t nr, WS2812_HSV_t hsv_col, uint8_t refresh)
void UB_WS2812_All_Led_HSV (WS2812_HSV_t hsv_col, uint8_t refresh)
void UB_WS2812_Shift_Left (void)
void UB_WS2812_Shift_Right (void)
void UB_WS2812_Rotate_Left (void)
void UB_WS2812_Rotate_Right (void)
ErrorStatus UB_WS2812_Check_Len (void)
void d_printArray (void)
void WS2812_DMA_CH1_ISR (void)
void WS2812_DMA_CH2_ISR (void)
void WS2812_DMA_CH3_ISR (void)
void WS2812_DMA_CH4_ISR (void)
void EXTI9_5_IRQHandler (void)
Variables
uint32_t ws2812_dma_status
uint16_t WS2812_TIMER_BUF [WS2812_TIMER_BUF_LEN]
uint8_t ws2812_channel
WS2812_RGB_t * ws2812_ptr
uint32_t ws2812_maxanz
uint32_t ws2812_len
WS2812_CHAIN_LEN_t WS2812_CHAIN_LEN
WS2812_RGB_t WS2812_LED_BUF_CH1 [WS2812_LED_MAX_ANZ]
WS2812_RGB_t WS2812_LED_BUF_CH2 [WS2812_LED_MAX_ANZ]
WS2812_RGB_t WS2812_LED_BUF_CH3 [WS2812_LED_MAX_ANZ]
WS2812_RGB_t WS2812_LED_BUF_CH4 [WS2812_LED_MAX_ANZ]
Detailed Description
This file includes the ws2812 LED functions Module: GPIO, TIM, DMA, MISC, EXTI, SYSCFG.
Author
UB <mc-4u(@)t-online.de> (v1.3)
Michael Sauer sauer.nosp@m..uet.nosp@m.ersen.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
21.09.2014 - 4 Channel version
Definition in file stm32_ub_ws2812.c.
Function Documentation
void d_printArray (void)
Definition at line 1179 of file stm32_ub_ws2812.c.
References WS2812_RGB_t::blue, buf, WS2812_CHAIN_LEN_t::ch1, WS2812_RGB_t::green, Log(), WS2812_RGB_t::red, and VERBOSE.
Referenced by ML_ParseCommands().
void EXTI9_5_IRQHandler (void)
Definition at line 1553 of file stm32_ub_ws2812.c.
References DMA_GetCurrDataCounter(), EXTI_ClearITPendingBit(), EXTI_GetITStatus(), WS2812_CH1_EXTI_LINE, WS2812_CH2_EXTI_LINE, WS2812_CH3_EXTI_LINE, WS2812_CH4_EXTI_LINE, ws2812_channel, WS2812_DMA_CH1_CHANNEL, WS2812_DMA_CH2_CHANNEL, WS2812_DMA_CH3_CHANNEL, WS2812_DMA_CH4_CHANNEL, ws2812_len, and WS2812_TIMER_BUF_LEN.
void p_WS2812_calcTimerBuf (uint8_t mode)
Definition at line 882 of file stm32_ub_ws2812.c.
References WS2812_RGB_t::blue, WS2812_RGB_t::green, WS2812_RGB_t::red, WS2812_BIT_PER_LED, ws2812_channel, WS2812_HI_TIME, WS2812_LO_TIME, ws2812_maxanz, WS2812_PAUSE_ANZ, and WS2812_TIMER_BUF.
Referenced by UB_WS2812_Check_Len(), and UB_WS2812_Refresh().
void p_WS2812_clearAll (void)
Definition at line 781 of file stm32_ub_ws2812.c.
References WS2812_CHAIN_LEN_t::ch1, WS2812_CHAIN_LEN_t::ch2, WS2812_CHAIN_LEN_t::ch3, WS2812_CHAIN_LEN_t::ch4, p_WS2812_DMA_Start(), UB_WS2812_All_Led_RGB(), UB_WS2812_SetChannel(), ws2812_dma_status, and WS2812_RGB_COL_OFF.
Referenced by UB_WS2812_Init().
void p_WS2812_clearBuff (void)
Definition at line 865 of file stm32_ub_ws2812.c.
References WS2812_TIMER_BUF, and WS2812_TIMER_BUF_LEN.
Referenced by UB_WS2812_Check_Len(), and UB_WS2812_Init().
void p_WS2812_DMA_Start (void)
Definition at line 1025 of file stm32_ub_ws2812.c.
References DMA_Cmd(), DMA_IT_TC, DMA_ITConfig(), p_WS2812_InitDMA(), TIM_Cmd(), ws2812_channel, WS2812_DMA_CH1_CHANNEL, WS2812_DMA_CH2_CHANNEL, WS2812_DMA_CH3_CHANNEL, WS2812_DMA_CH4_CHANNEL, ws2812_dma_status, WS2812_TIM, and WS2812_TIM_CH2.
Referenced by p_WS2812_clearAll(), UB_WS2812_Check_Len(), and UB_WS2812_Refresh().
void p_WS2812_InitDMA (void)
Definition at line 1262 of file stm32_ub_ws2812.c.
References buf, WS2812_CHAIN_LEN_t::ch1, WS2812_CHAIN_LEN_t::ch2, WS2812_CHAIN_LEN_t::ch3, WS2812_CHAIN_LEN_t::ch4, DMA_InitTypeDef::DMA_BufferSize, DMA_Cmd(), DMA_DeInit(), DMA_InitTypeDef::DMA_DIR, DMA_DIR_PeripheralDST, DMA_Init(), DMA_InitTypeDef::DMA_M2M, DMA_M2M_Disable, DMA_InitTypeDef::DMA_MemoryBaseAddr, DMA_InitTypeDef::DMA_MemoryDataSize, DMA_MemoryDataSize_HalfWord, DMA_InitTypeDef::DMA_MemoryInc, DMA_MemoryInc_Enable, DMA_InitTypeDef::DMA_Mode, DMA_Mode_Normal, DMA_InitTypeDef::DMA_PeripheralBaseAddr, DMA_InitTypeDef::DMA_PeripheralDataSize, DMA_PeripheralDataSize_HalfWord, DMA_InitTypeDef::DMA_PeripheralInc, DMA_PeripheralInc_Disable, DMA_InitTypeDef::DMA_Priority, DMA_Priority_VeryHigh, Log(), WS2812_BIT_PER_LED, ws2812_channel, WS2812_DMA_CH1_CHANNEL, WS2812_DMA_CH2_CHANNEL, WS2812_DMA_CH3_CHANNEL, WS2812_DMA_CH4_CHANNEL, WS2812_PAUSE_ANZ, WS2812_TIM_CCR_REG1, WS2812_TIM_CCR_REG2, WS2812_TIM_CCR_REG3, WS2812_TIM_CCR_REG4, and WS2812_TIMER_BUF.
Referenced by p_WS2812_DMA_Start(), and UB_WS2812_Init().
void p_WS2812_InitEXTI (void)
Definition at line 1422 of file stm32_ub_ws2812.c.
References EXTI_Init(), EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, EXTI_Trigger_Falling, WS2812_CH1_EXTI_LINE, WS2812_CH2_EXTI_LINE, WS2812_CH3_EXTI_LINE, and WS2812_CH4_EXTI_LINE.
Referenced by UB_WS2812_Init().
void p_WS2812_InitIO (void)
Definition at line 1071 of file stm32_ub_ws2812.c.
References GPIO_EXTILineConfig(), GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF_PP, GPIO_Mode_IN_FLOATING, GPIO_InitTypeDef::GPIO_Pin, GPIO_ResetBits(), GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, RCC_APB2Periph_AFIO, RCC_APB2PeriphClockCmd(), WS2812_CH1_CLOCK, WS2812_CH1_EXTI_CLOCK, WS2812_CH1_EXTI_PIN, WS2812_CH1_EXTI_PINSRC, WS2812_CH1_EXTI_PORT, WS2812_CH1_EXTI_SOURCE, WS2812_CH1_PIN, WS2812_CH1_PORT, WS2812_CH2_CLOCK, WS2812_CH2_EXTI_PIN, WS2812_CH2_EXTI_PINSRC, WS2812_CH2_EXTI_PORT, WS2812_CH2_PIN, WS2812_CH2_PORT, WS2812_CH3_CLOCK, WS2812_CH3_EXTI_PIN, WS2812_CH3_EXTI_PINSRC, WS2812_CH3_EXTI_PORT, WS2812_CH3_PIN, WS2812_CH3_PORT, WS2812_CH4_CLOCK, WS2812_CH4_EXTI_PIN, WS2812_CH4_EXTI_PINSRC, WS2812_CH4_EXTI_PORT, WS2812_CH4_PIN, and WS2812_CH4_PORT.
Referenced by UB_WS2812_Init().
void p_WS2812_InitNVIC (void)
Definition at line 1359 of file stm32_ub_ws2812.c.
References NVIC_Init(), NVIC_InitTypeDef::NVIC_IRQChannel, NVIC_InitTypeDef::NVIC_IRQChannelCmd, NVIC_InitTypeDef::NVIC_IRQChannelPreemptionPriority, NVIC_InitTypeDef::NVIC_IRQChannelSubPriority, TIM_DMACmd(), WS2812_CH1_EXTI_IRQ, WS2812_DMA_CH1_IRQn, WS2812_DMA_CH2_IRQn, WS2812_DMA_CH3_IRQn, WS2812_DMA_CH4_IRQn, WS2812_TIM, WS2812_TIM_CH2, WS2812_TIM_DMA_TRG1, WS2812_TIM_DMA_TRG2, WS2812_TIM_DMA_TRG3, and WS2812_TIM_DMA_TRG4.
Referenced by UB_WS2812_Init().
void p_WS2812_InitTIM (void)
Definition at line 1211 of file stm32_ub_ws2812.c.
References RCC_AHBPeriphClockCmd(), RCC_APB1PeriphClockCmd(), TIM_ARRPreloadConfig(), TIM_TimeBaseInitTypeDef::TIM_ClockDivision, TIM_TimeBaseInitTypeDef::TIM_CounterMode, TIM_CounterMode_Up, TIM_OC1Init(), TIM_OC1PreloadConfig(), TIM_OC2Init(), TIM_OC2PreloadConfig(), TIM_OC3Init(), TIM_OC3PreloadConfig(), TIM_OC4Init(), TIM_OC4PreloadConfig(), TIM_OCInitTypeDef::TIM_OCMode, TIM_OCMode_PWM1, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_OCPolarity_High, TIM_OCPreload_Enable, TIM_OCInitTypeDef::TIM_OutputState, TIM_OutputState_Enable, TIM_TimeBaseInitTypeDef::TIM_Period, TIM_TimeBaseInitTypeDef::TIM_Prescaler, TIM_OCInitTypeDef::TIM_Pulse, TIM_TimeBaseInit(), WS2812_DMA_CLOCK, WS2812_TIM, WS2812_TIM_CH2, WS2812_TIM_CLOCK, WS2812_TIM_CLOCK_CH2, WS2812_TIM_PERIODE, and WS2812_TIM_PRESCALE.
Referenced by UB_WS2812_Init().
void UB_WS2812_All_Led_HSV (WS2812_HSV_t hsv_col, uint8_t refresh)
Definition at line 492 of file stm32_ub_ws2812.c.
References UB_WS2812_Refresh(), UB_WS2812_RGB_2_HSV(), ws2812_channel, and ws2812_maxanz.
void UB_WS2812_All_Led_RGB (WS2812_RGB_t rgb_col, uint8_t refresh)
Definition at line 448 of file stm32_ub_ws2812.c.
References UB_WS2812_Refresh(), ws2812_channel, and ws2812_maxanz.
Referenced by p_WS2812_clearAll().
ErrorStatus UB_WS2812_Check_Len (void)
Definition at line 614 of file stm32_ub_ws2812.c.
References WS2812_CHAIN_LEN_t::ch1, WS2812_CHAIN_LEN_t::ch2, WS2812_CHAIN_LEN_t::ch3, WS2812_CHAIN_LEN_t::ch4, p_WS2812_calcTimerBuf(), p_WS2812_clearBuff(), p_WS2812_DMA_Start(), UB_WS2812_SetChannel(), WS2812_BIT_PER_LED, ws2812_dma_status, WS2812_LED_MAX_ANZ, ws2812_len, and WS2812_RGB_COL_OFF.
Referenced by UB_WS2812_Init().
void UB_WS2812_ClearChannel (uint8_t ch)
Definition at line 187 of file stm32_ub_ws2812.c.
References WS2812_RGB_t::blue, WS2812_CHAIN_LEN_t::ch1, WS2812_CHAIN_LEN_t::ch2, WS2812_CHAIN_LEN_t::ch3, WS2812_CHAIN_LEN_t::ch4, WS2812_RGB_t::green, and WS2812_RGB_t::red.
void UB_WS2812_FadeOut (uint8_t ch, uint8_t numfade, uint8_t count)
Definition at line 268 of file stm32_ub_ws2812.c.
References WS2812_RGB_t::blue, WS2812_RGB_t::green, and WS2812_RGB_t::red.
ErrorStatus UB_WS2812_Init (void)
Definition at line 80 of file stm32_ub_ws2812.c.
References WS2812_CHAIN_LEN_t::ch1, WS2812_CHAIN_LEN_t::ch2, WS2812_CHAIN_LEN_t::ch3, WS2812_CHAIN_LEN_t::ch4, p_WS2812_clearAll(), p_WS2812_clearBuff(), p_WS2812_InitDMA(), p_WS2812_InitEXTI(), p_WS2812_InitIO(), p_WS2812_InitNVIC(), p_WS2812_InitTIM(), UB_WS2812_Check_Len(), UB_WS2812_SetChannel(), ws2812_channel, ws2812_dma_status, WS2812_LED_MAX_ANZ, ws2812_len, ws2812_maxanz, and WS2812_RGB_COL_OFF.
Referenced by main().
void UB_WS2812_One_Led_HSV (uint32_t nr, WS2812_HSV_t hsv_col, uint8_t refresh)
Definition at line 469 of file stm32_ub_ws2812.c.
References UB_WS2812_Refresh(), UB_WS2812_RGB_2_HSV(), ws2812_channel, and ws2812_maxanz.
void UB_WS2812_One_Led_RGB (uint32_t nr, WS2812_RGB_t rgb_col, uint8_t refresh)
Definition at line 429 of file stm32_ub_ws2812.c.
References UB_WS2812_Refresh(), ws2812_channel, and ws2812_maxanz.
void UB_WS2812_Refresh (void)
Definition at line 341 of file stm32_ub_ws2812.c.
References p_WS2812_calcTimerBuf(), p_WS2812_DMA_Start(), ws2812_channel, and ws2812_dma_status.
Referenced by UB_WS2812_All_Led_HSV(), UB_WS2812_All_Led_RGB(), UB_WS2812_One_Led_HSV(), UB_WS2812_One_Led_RGB(), UB_WS2812_Rotate_Left(), UB_WS2812_Rotate_Right(), UB_WS2812_Shift_Left(), and UB_WS2812_Shift_Right().
void UB_WS2812_RGB_2_HSV (WS2812_HSV_t hsv_col, WS2812_RGB_t * rgb_col)
Definition at line 361 of file stm32_ub_ws2812.c.
References WS2812_RGB_t::blue, WS2812_RGB_t::green, WS2812_HSV_t::h, WS2812_RGB_t::red, WS2812_HSV_t::s, and WS2812_HSV_t::v.
Referenced by UB_WS2812_All_Led_HSV(), and UB_WS2812_One_Led_HSV().
void UB_WS2812_Rotate_Left (void)
Definition at line 562 of file stm32_ub_ws2812.c.
References UB_WS2812_Refresh(), ws2812_channel, and ws2812_maxanz.
void UB_WS2812_Rotate_Right (void)
Definition at line 587 of file stm32_ub_ws2812.c.
References UB_WS2812_Refresh(), ws2812_channel, and ws2812_maxanz.
void UB_WS2812_SetChannel (uint8_t ch)
Definition at line 232 of file stm32_ub_ws2812.c.
References WS2812_CHAIN_LEN_t::ch1, WS2812_CHAIN_LEN_t::ch2, WS2812_CHAIN_LEN_t::ch3, WS2812_CHAIN_LEN_t::ch4, ws2812_channel, and ws2812_maxanz.
Referenced by p_WS2812_clearAll(), UB_WS2812_Check_Len(), and UB_WS2812_Init().
void UB_WS2812_SetPixel (uint8_t ch, uint16_t pixel, uint8_t red, uint8_t green, uint8_t blue)
Definition at line 161 of file stm32_ub_ws2812.c.
References WS2812_RGB_t::blue, WS2812_RGB_t::green, and WS2812_RGB_t::red.
void UB_WS2812_Shift_Left (void)
Definition at line 514 of file stm32_ub_ws2812.c.
References UB_WS2812_Refresh(), ws2812_channel, ws2812_maxanz, and WS2812_RGB_COL_OFF.
void UB_WS2812_Shift_Right (void)
Definition at line 538 of file stm32_ub_ws2812.c.
References UB_WS2812_Refresh(), ws2812_channel, ws2812_maxanz, and WS2812_RGB_COL_OFF.
void WS2812_DMA_CH1_ISR (void)
Definition at line 1461 of file stm32_ub_ws2812.c.
References DMA_ClearFlag(), DMA_Cmd(), DMA_GetITStatus(), TIM_Cmd(), WS2812_DMA_CH1_CHANNEL, WS2812_DMA_CH1_IRQ_FLAG, ws2812_dma_status, and WS2812_TIM.
void WS2812_DMA_CH2_ISR (void)
Definition at line 1484 of file stm32_ub_ws2812.c.
References DMA_ClearFlag(), DMA_Cmd(), DMA_GetITStatus(), TIM_Cmd(), WS2812_DMA_CH2_CHANNEL, WS2812_DMA_CH2_IRQ_FLAG, ws2812_dma_status, and WS2812_TIM_CH2.
void WS2812_DMA_CH3_ISR (void)
Definition at line 1507 of file stm32_ub_ws2812.c.
References DMA_ClearFlag(), DMA_Cmd(), DMA_GetITStatus(), TIM_Cmd(), WS2812_DMA_CH3_CHANNEL, WS2812_DMA_CH3_IRQ_FLAG, ws2812_dma_status, and WS2812_TIM.
void WS2812_DMA_CH4_ISR (void)
Definition at line 1530 of file stm32_ub_ws2812.c.
References DMA_ClearFlag(), DMA_Cmd(), DMA_GetITStatus(), TIM_Cmd(), WS2812_DMA_CH4_CHANNEL, WS2812_DMA_CH4_IRQ_FLAG, ws2812_dma_status, and WS2812_TIM.
Variable Documentation
WS2812_CHAIN_LEN_t WS2812_CHAIN_LEN
Definition at line 33 of file stm32_ub_ws2812.c.
uint8_t ws2812_channel
Definition at line 27 of file stm32_ub_ws2812.c.
Referenced by EXTI9_5_IRQHandler(), p_WS2812_calcTimerBuf(), p_WS2812_DMA_Start(), p_WS2812_InitDMA(), UB_WS2812_All_Led_HSV(), UB_WS2812_All_Led_RGB(), UB_WS2812_Init(), UB_WS2812_One_Led_HSV(), UB_WS2812_One_Led_RGB(), UB_WS2812_Refresh(), UB_WS2812_Rotate_Left(), UB_WS2812_Rotate_Right(), UB_WS2812_SetChannel(), UB_WS2812_Shift_Left(), and UB_WS2812_Shift_Right().
uint32_t ws2812_dma_status
Definition at line 25 of file stm32_ub_ws2812.c.
Referenced by p_WS2812_clearAll(), p_WS2812_DMA_Start(), UB_WS2812_Check_Len(), UB_WS2812_Init(), UB_WS2812_Refresh(), WS2812_DMA_CH1_ISR(), WS2812_DMA_CH2_ISR(), WS2812_DMA_CH3_ISR(), and WS2812_DMA_CH4_ISR().
WS2812_RGB_t WS2812_LED_BUF_CH1[WS2812_LED_MAX_ANZ]
Definition at line 36 of file stm32_ub_ws2812.c.
WS2812_RGB_t WS2812_LED_BUF_CH2[WS2812_LED_MAX_ANZ]
Definition at line 41 of file stm32_ub_ws2812.c.
WS2812_RGB_t WS2812_LED_BUF_CH3[WS2812_LED_MAX_ANZ]
Definition at line 46 of file stm32_ub_ws2812.c.
WS2812_RGB_t WS2812_LED_BUF_CH4[WS2812_LED_MAX_ANZ]
Definition at line 52 of file stm32_ub_ws2812.c.
uint32_t ws2812_len
Definition at line 30 of file stm32_ub_ws2812.c.
Referenced by EXTI9_5_IRQHandler(), UB_WS2812_Check_Len(), and UB_WS2812_Init().
uint32_t ws2812_maxanz
Definition at line 29 of file stm32_ub_ws2812.c.
Referenced by p_WS2812_calcTimerBuf(), UB_WS2812_All_Led_HSV(), UB_WS2812_All_Led_RGB(), UB_WS2812_Init(), UB_WS2812_One_Led_HSV(), UB_WS2812_One_Led_RGB(), UB_WS2812_Rotate_Left(), UB_WS2812_Rotate_Right(), UB_WS2812_SetChannel(), UB_WS2812_Shift_Left(), and UB_WS2812_Shift_Right().
WS2812_RGB_t* ws2812_ptr
Definition at line 28 of file stm32_ub_ws2812.c.
uint16_t WS2812_TIMER_BUF[WS2812_TIMER_BUF_LEN]
Definition at line 26 of file stm32_ub_ws2812.c.
Referenced by p_WS2812_calcTimerBuf(), p_WS2812_clearBuff(), and p_WS2812_InitDMA().